var keys = [ "lesson", "Pinyin", "Chinese(simplified)", "English" ];
var ignoreKeys = [ true, false, false, false ];
var words = [
    { "lesson":"1", "Pinyin":"nǐ", "Chinese(simplified)":"你", "English":"you" },
    { "lesson":"1", "Pinyin":"hǎo", "Chinese(simplified)":"好", "English":"good" },
    { "lesson":"1", "Pinyin":"zàijiàn", "Chinese(simplified)":"再见", "English":"goodbye" },
    { "lesson":"1", "Pinyin":"búkèqi", "Chinese(simplified)":"不客气", "English":"you're welcome" },
    { "lesson":"1", "Pinyin":"bù", "Chinese(simplified)":"不", "English":"no" },
    { "lesson":"1", "Pinyin":"kèqi", "Chinese(simplified)":"客气", "English":"polite" },
    { "lesson":"2", "Pinyin":"jiào", "Chinese(simplified)":"叫", "English":"called" },
    { "lesson":"2", "Pinyin":"shénme", "Chinese(simplified)":"什么", "English":"what" },
    { "lesson":"2", "Pinyin":"míngzi", "Chinese(simplified)":"名字", "English":"name" },
    { "lesson":"2", "Pinyin":"wǒ", "Chinese(simplified)":"我", "English":"I,me" },
    { "lesson":"2", "Pinyin":"Líndá", "Chinese(simplified)":"林达", "English":"Linda" },
    { "lesson":"2", "Pinyin":"Mǎkě", "Chinese(simplified)":"马可", "English":"Mark" },
    { "lesson":"2", "Pinyin":"nǐmen", "Chinese(simplified)":"你们", "English":"you (plural)" },
    { "lesson":"2", "Pinyin":"lǎoshī", "Chinese(simplified)":"老师", "English":"teacher" },
    { "lesson":"2", "Pinyin":"nín", "Chinese(simplified)":"您", "English":"you (polite)" },
    { "lesson":"2", "Pinyin":"guì", "Chinese(simplified)":"贵", "English":"honourable" },
    { "lesson":"2", "Pinyin":"xìng", "Chinese(simplified)":"姓", "English":"surname" },
    { "lesson":"2", "Pinyin":"LǐLán", "Chinese(simplified)":"李兰", "English":"Li Lan" },
    { "lesson":"3", "Pinyin":"WángDàyáng", "Chinese(simplified)":"王大阳", "English":"Wang Dayang" },
    { "lesson":"3", "Pinyin":"hěn", "Chinese(simplified)":"很", "English":"very" },
    { "lesson":"3", "Pinyin":"gāoxìng", "Chinese(simplified)":"高兴", "English":"glad" },
    { "lesson":"3", "Pinyin":"rènshi", "Chinese(simplified)":"认识", "English":"to get to know" },
    { "lesson":"3", "Pinyin":"yě", "Chinese(simplified)":"也", "English":"also" },
    { "lesson":"3", "Pinyin":"shì", "Chinese(simplified)":"是", "English":"to be" },
    { "lesson":"3", "Pinyin":"nǎ", "Chinese(simplified)":"哪", "English":"which" },
    { "lesson":"3", "Pinyin":"Zhōngguórén", "Chinese(simplified)":"中国人", "English":"Chinese person/people" },
    { "lesson":"3", "Pinyin":"Zhōngguó", "Chinese(simplified)":"中国", "English":"China" },
    { "lesson":"3", "Pinyin":"rén", "Chinese(simplified)":"人", "English":"person/people" },
    { "lesson":"3", "Pinyin":"ne", "Chinese(simplified)":"呢", "English":"interrogative particle" },
    { "lesson":"3", "Pinyin":"Yīngguórén", "Chinese(simplified)":"英国人", "English":"British" },
    { "lesson":"3", "Pinyin":"Yīngguó", "Chinese(simplified)":"英国", "English":"UK" },
    { "lesson":"3", "Pinyin":"Dàwèi", "Chinese(simplified)":"大卫", "English":"David" },
    { "lesson":"3", "Pinyin":"xuésheng", "Chinese(simplified)":"学生", "English":"student" },
    { "lesson":"3", "Pinyin":"xuéxí", "Chinese(simplified)":"学习", "English":"to study" },
    { "lesson":"3", "Pinyin":"Hànyǔ", "Chinese(simplified)":"汉语", "English":"Chinese language" },
    { "lesson":"3", "Pinyin":"Yīngyǔ", "Chinese(simplified)":"英语", "English":"English language" },
    { "lesson":"3", "Pinyin":"zhè", "Chinese(simplified)":"这", "English":"this" },
    { "lesson":"3", "Pinyin":"ma", "Chinese(simplified)":"吗", "English":"interrogative particle" }
];
