var keys = [ "lesson", "Pinyin", "Chinese(simplified)", "English" ];
var ignoreKeys = [ true, false, false, false ];
var words = [
    { "lesson":"1", "Pinyin":"nǐ", "Chinese(simplified)":"你", "English":"you" },
    { "lesson":"1", "Pinyin":"hǎo", "Chinese(simplified)":"好", "English":"good" },
    { "lesson":"1", "Pinyin":"zàijiàn", "Chinese(simplified)":"再见", "English":"goodbye" },
    { "lesson":"1", "Pinyin":"búkèqi", "Chinese(simplified)":"不客气", "English":"you're welcome" },
    { "lesson":"1", "Pinyin":"bù", "Chinese(simplified)":"不", "English":"no" },
    { "lesson":"1", "Pinyin":"kèqi", "Chinese(simplified)":"客气", "English":"polite" },
    { "lesson":"2", "Pinyin":"jiào", "Chinese(simplified)":"叫", "English":"called" },
    { "lesson":"2", "Pinyin":"shénme", "Chinese(simplified)":"什么", "English":"what" },
    { "lesson":"2", "Pinyin":"míngzi", "Chinese(simplified)":"名字", "English":"name" },
    { "lesson":"2", "Pinyin":"wǒ", "Chinese(simplified)":"我", "English":"I,me" },
    { "lesson":"2", "Pinyin":"Líndá", "Chinese(simplified)":"林达", "English":"Linda" },
    { "lesson":"2", "Pinyin":"Mǎkě", "Chinese(simplified)":"马可", "English":"Mark" },
    { "lesson":"2", "Pinyin":"nǐmen", "Chinese(simplified)":"你们", "English":"you (plural)" },
    { "lesson":"2", "Pinyin":"lǎoshī", "Chinese(simplified)":"老师", "English":"teacher" },
    { "lesson":"2", "Pinyin":"nín", "Chinese(simplified)":"您", "English":"you (polite)" },
    { "lesson":"2", "Pinyin":"guì", "Chinese(simplified)":"贵", "English":"honourable" },
    { "lesson":"2", "Pinyin":"xìng", "Chinese(simplified)":"姓", "English":"surname" },
    { "lesson":"2", "Pinyin":"LǐLán", "Chinese(simplified)":"李兰", "English":"Li Lan" },
    { "lesson":"3", "Pinyin":"WángDàyáng", "Chinese(simplified)":"王大阳", "English":"Wang Dayang" },
    { "lesson":"3", "Pinyin":"hěn", "Chinese(simplified)":"很", "English":"very" },
    { "lesson":"3", "Pinyin":"gāoxìng", "Chinese(simplified)":"高兴", "English":"glad" },
    { "lesson":"3", "Pinyin":"rènshi", "Chinese(simplified)":"认识", "English":"to get to know" },
    { "lesson":"3", "Pinyin":"yě", "Chinese(simplified)":"也", "English":"also" },
    { "lesson":"3", "Pinyin":"shì", "Chinese(simplified)":"是", "English":"to be" },
    { "lesson":"3", "Pinyin":"nǎ", "Chinese(simplified)":"哪", "English":"which" },
    { "lesson":"3", "Pinyin":"Zhōngguórén", "Chinese(simplified)":"中国人", "English":"Chinese person/people" },
    { "lesson":"3", "Pinyin":"Zhōngguó", "Chinese(simplified)":"中国", "English":"China" },
    { "lesson":"3", "Pinyin":"rén", "Chinese(simplified)":"人", "English":"person/people" },
    { "lesson":"3", "Pinyin":"ne", "Chinese(simplified)":"呢", "English":"interrogative particle" },
    { "lesson":"3", "Pinyin":"Yīngguórén", "Chinese(simplified)":"英国人", "English":"British" },
    { "lesson":"3", "Pinyin":"Yīngguó", "Chinese(simplified)":"英国", "English":"UK" },
    { "lesson":"3", "Pinyin":"Dàwèi", "Chinese(simplified)":"大卫", "English":"David" },
    { "lesson":"3", "Pinyin":"xuésheng", "Chinese(simplified)":"学生", "English":"student" },
    { "lesson":"3", "Pinyin":"xuéxí", "Chinese(simplified)":"学习", "English":"to study" },
    { "lesson":"3", "Pinyin":"Hànyǔ", "Chinese(simplified)":"汉语", "English":"Chinese language" },
    { "lesson":"3", "Pinyin":"Yīngyǔ", "Chinese(simplified)":"英语", "English":"English language" },
    { "lesson":"3", "Pinyin":"zhè", "Chinese(simplified)":"这", "English":"this" },
    { "lesson":"3", "Pinyin":"ma", "Chinese(simplified)":"吗", "English":"interrogative particle" },
    { "lesson":"4", "Pinyin":"zhàopiàn", "Chinese(simplified)":"照片", "English":"photo" },
    { "lesson":"4", "Pinyin":"a", "Chinese(simplified)":"啊", "English":"oh" },
    { "lesson":"4", "Pinyin":"de", "Chinese(simplified)":"的", "English":"particle" },
    { "lesson":"4", "Pinyin":"tā", "Chinese(simplified)":"他", "English":"he" },
    { "lesson":"4", "Pinyin":"bàba", "Chinese(simplified)":"爸爸", "English":"father" },
    { "lesson":"4", "Pinyin":"yéye", "Chinese(simplified)":"爷爷", "English":"grandfather" },
    { "lesson":"4", "Pinyin":"tā", "Chinese(simplified)":"她", "English":"she" },
    { "lesson":"4", "Pinyin":"māma", "Chinese(simplified)":"妈妈", "English":"mother" },
    { "lesson":"4", "Pinyin":"nà", "Chinese(simplified)":"那", "English":"that" },
    { "lesson":"4", "Pinyin":"nǎinai", "Chinese(simplified)":"奶奶", "English":"grandmother" },
    { "lesson":"4", "Pinyin":"duì", "Chinese(simplified)":"对", "English":"correct" },
    { "lesson":"4", "Pinyin":"yǒu", "Chinese(simplified)":"有", "English":"to have" },
    { "lesson":"4", "Pinyin":"mèimei", "Chinese(simplified)":"妹妹", "English":"younger sister" },
    { "lesson":"4", "Pinyin":"liǎng", "Chinese(simplified)":"两", "English":"two (of)" },
    { "lesson":"4", "Pinyin":"gè", "Chinese(simplified)":"个", "English":"measure word(generic)" },
    { "lesson":"4", "Pinyin":"jiějie", "Chinese(simplified)":"姐姐", "English":"elder sister" },
    { "lesson":"4", "Pinyin":"méiyǒu", "Chinese(simplified)":"没有", "English":"don't have" },
    { "lesson":"4", "Pinyin":"hé", "Chinese(simplified)":"和", "English":"and" },
    { "lesson":"4", "Pinyin":"gēge", "Chinese(simplified)":"哥哥", "English":"elder brother" },
    { "lesson":"4", "Pinyin":"dìdi", "Chinese(simplified)":"弟弟", "English":"younger brother" },
    { "lesson":"5", "Pinyin":"māo", "Chinese(simplified)":"猫", "English":"cat" },
    { "lesson":"5", "Pinyin":"zhī", "Chinese(simplified)":"只", "English":"measure word(animals)" },
    { "lesson":"5", "Pinyin":"gǒu", "Chinese(simplified)":"狗", "English":"dog" },
    { "lesson":"5", "Pinyin":"kěshì", "Chinese(simplified)":"可是", "English":"but" },
    { "lesson":"5", "Pinyin":"niǎo", "Chinese(simplified)":"鸟", "English":"bird" },
    { "lesson":"5", "Pinyin":"tā", "Chinese(simplified)":"它", "English":"it" },
    { "lesson":"5", "Pinyin":"Mīmi", "Chinese(simplified)":"咪咪", "English":"Mimi" },
    { "lesson":"5", "Pinyin":"hěn", "Chinese(simplified)":"很", "English":"very" },
    { "lesson":"5", "Pinyin":"yǒuyìsi", "Chinese(simplified)":"有意思", "English":"interesting" },
    { "lesson":"5", "Pinyin":"Kǎlā", "Chinese(simplified)":"卡拉", "English":"Kala" },
    { "lesson":"5", "Pinyin":"dà", "Chinese(simplified)":"大", "English":"big" },
    { "lesson":"5", "Pinyin":"xiǎo", "Chinese(simplified)":"小", "English":"small" },
    { "lesson":"5", "Pinyin":"piàoliang", "Chinese(simplified)":"漂亮", "English":"beautiful" },
    { "lesson":"5", "Pinyin":"cōngming", "Chinese(simplified)":"聪明", "English":"clever" },
    { "lesson":"5", "Pinyin":"huì", "Chinese(simplified)":"会", "English":"can (to have ability to)" },
    { "lesson":"5", "Pinyin":"yóuyǒng", "Chinese(simplified)":"游泳", "English":"to swim" },
    { "lesson":"5", "Pinyin":"shuō", "Chinese(simplified)":"说", "English":"to speak" },
    { "lesson":"6", "Pinyin":"hǎojiǔ", "Chinese(simplified)":"好久", "English":"a long time" },
    { "lesson":"6", "Pinyin":"jiàn", "Chinese(simplified)":"见", "English":"to see" },
    { "lesson":"6", "Pinyin":"jīntiān", "Chinese(simplified)":"今天", "English":"today" },
    { "lesson":"6", "Pinyin":"máng", "Chinese(simplified)":"忙", "English":"busy" },
    { "lesson":"6", "Pinyin":"míngtiān", "Chinese(simplified)":"明天", "English":"tomorrow" },
    { "lesson":"6", "Pinyin":"xīngqīliù", "Chinese(simplified)":"星期六", "English":"Saturday" },
    { "lesson":"6", "Pinyin":"shēngrì", "Chinese(simplified)":"生日", "English":"birthday" },
    { "lesson":"6", "Pinyin":"jǐ", "Chinese(simplified)":"几", "English":"which (month/date)" },
    { "lesson":"6", "Pinyin":"yuè", "Chinese(simplified)":"月", "English":"month" },
    { "lesson":"6", "Pinyin":"hào", "Chinese(simplified)":"号", "English":"date" },
    { "lesson":"6", "Pinyin":"qǐng", "Chinese(simplified)":"请", "English":"to invite" },
    { "lesson":"6", "Pinyin":"chī", "Chinese(simplified)":"吃", "English":"to eat" },
    { "lesson":"6", "Pinyin":"dàn'gāo", "Chinese(simplified)":"蛋糕", "English":"cake" },
    { "lesson":"6", "Pinyin":"sòng", "Chinese(simplified)":"送", "English":"to give (a gift)" },
    { "lesson":"6", "Pinyin":"lǐwù", "Chinese(simplified)":"礼物", "English":"gift" },
    { "lesson":"7", "Pinyin":"diǎn", "Chinese(simplified)":"点", "English":"o'clock" },
    { "lesson":"7", "Pinyin":"qǐchuáng", "Chinese(simplified)":"起床", "English":"to get up" },
    { "lesson":"7", "Pinyin":"bàn", "Chinese(simplified)":"半", "English":"half" },
    { "lesson":"7", "Pinyin":"zuǒyòu", "Chinese(simplified)":"左右", "English":"approximate (number)" },
    { "lesson":"7", "Pinyin":"zhēn", "Chinese(simplified)":"真", "English":"really" },
    { "lesson":"7", "Pinyin":"zǎo", "Chinese(simplified)":"早", "English":"early" },
    { "lesson":"7", "Pinyin":"zǎofàn", "Chinese(simplified)":"早饭", "English":"breakfast" },
    { "lesson":"7", "Pinyin":"dào", "Chinese(simplified)":"到", "English":"to arrive" },
    { "lesson":"7", "Pinyin":"xuéxiào", "Chinese(simplified)":"学校", "English":"school" },
    { "lesson":"7", "Pinyin":"shíhou", "Chinese(simplified)":"时候", "English":"time" },
    { "lesson":"7", "Pinyin":"shàngkè", "Chinese(simplified)":"上课", "English":"start class" },
    { "lesson":"7", "Pinyin":"kè", "Chinese(simplified)":"刻", "English":"quarter (of an hour)" },
    { "lesson":"7", "Pinyin":"fēn", "Chinese(simplified)":"分", "English":"minute" },
    { "lesson":"7", "Pinyin":"xiàkè", "Chinese(simplified)":"下课", "English":"finish class" },
    { "lesson":"7", "Pinyin":"xiànzài", "Chinese(simplified)":"现在", "English":"now" },
    { "lesson":"7", "Pinyin":"chà", "Chinese(simplified)":"差", "English":"be short of" },
    { "lesson":"7", "Pinyin":"děi...le", "Chinese(simplified)":"得...了", "English":"must/have to" },
    { "lesson":"7", "Pinyin":"zǒu", "Chinese(simplified)":"走", "English":"to leave" },
    { "lesson":"7", "Pinyin":"huí", "Chinese(simplified)":"回", "English":"to return" },
    { "lesson":"7", "Pinyin":"jiā", "Chinese(simplified)":"家", "English":"home,family" },
    { "lesson":"7", "Pinyin":"zuò", "Chinese(simplified)":"做", "English":"to do" },
    { "lesson":"7", "Pinyin":"wǎnfàn", "Chinese(simplified)":"晚饭", "English":"dinner" },
    { "lesson":"8", "Pinyin":"shìjiè", "Chinese(simplified)":"世界", "English":"the world" },
    { "lesson":"8", "Pinyin":"dìtú", "Chinese(simplified)":"地图", "English":"map" },
    { "lesson":"8", "Pinyin":"lái", "Chinese(simplified)":"来", "English":"to come" },
    { "lesson":"8", "Pinyin":"kàn", "Chinese(simplified)":"看", "English":"to look" },
    { "lesson":"8", "Pinyin":"zhèr", "Chinese(simplified)":"这儿", "English":"here" },
    { "lesson":"8", "Pinyin":"zài", "Chinese(simplified)":"在", "English":"to be (in a place)" },
    { "lesson":"8", "Pinyin":"Ōuzhōu", "Chinese(simplified)":"欧洲", "English":"Europe" },
    { "lesson":"8", "Pinyin":"Yàzhōu", "Chinese(simplified)":"亚洲", "English":"Asia" },
    { "lesson":"8", "Pinyin":"dōngmiàn", "Chinese(simplified)":"东面", "English":"to the east of" },
    { "lesson":"8", "Pinyin":"miàn", "Chinese(simplified)":"面", "English":"side" },
    { "lesson":"8", "Pinyin":"Běijīng", "Chinese(simplified)":"北京", "English":"Beijing" },
    { "lesson":"8", "Pinyin":"Shànghǎi", "Chinese(simplified)":"上海", "English":"Shanghai" },
    { "lesson":"8", "Pinyin":"dōngbù", "Chinese(simplified)":"东部", "English":"eastern part" },
    { "lesson":"8", "Pinyin":"bù", "Chinese(simplified)":"部", "English":"part" },
    { "lesson":"8", "Pinyin":"dǎsuàn", "Chinese(simplified)":"打算", "English":"to plan" },
    { "lesson":"8", "Pinyin":"qù", "Chinese(simplified)":"去", "English":"to go" },
    { "lesson":"8", "Pinyin":"lüxíng", "Chinese(simplified)":"旅行", "English":"to travel, trip" },
    { "lesson":"8", "Pinyin":"Xī'ān", "Chinese(simplified)":"西安", "English":"Xi'an" },
    { "lesson":"8", "Pinyin":"xībù", "Chinese(simplified)":"西部", "English":"western part" },
    { "lesson":"8", "Pinyin":"péngyou", "Chinese(simplified)":"朋友", "English":"friend" },
    { "lesson":"8", "Pinyin":"nǎr", "Chinese(simplified)":"哪儿", "English":"where" },
    { "lesson":"8", "Pinyin":"gōngzuò", "Chinese(simplified)":"工作", "English":"to work" },
    { "lesson":"8", "Pinyin":"Hāěrbīn", "Chinese(simplified)":"哈尔滨", "English":"Haerbin" },
    { "lesson":"8", "Pinyin":"shéi/shuí", "Chinese(simplified)":"谁", "English":"who" },
    { "lesson":"8", "Pinyin":"běifāng", "Chinese(simplified)":"北方", "English":"north" },
    { "lesson":"8", "Pinyin":"dōngtіān", "Chinese(simplified)":"冬天", "English":"winter" },
    { "lesson":"8", "Pinyin":"tiānqí", "Chinese(simplified)":"天气", "English":"weather" },
    { "lesson":"8", "Pinyin":"lěng", "Chinese(simplified)":"冷", "English":"cold" },
    { "lesson":"8", "Pinyin":"xǐhuan", "Chinese(simplified)":"喜欢", "English":"to like" },
    { "lesson":"8", "Pinyin":"nánfāng", "Chinese(simplified)":"南方", "English":"south" }
];
