var keys = [ "lesson", "pinyin", "chinese", "english" ];
var ignoreKeys = [ true, false, false, false ];
var words = [
    { "lesson":"1", "pinyin":"nǐ", "chinese":"你", "english":"you" },
    { "lesson":"1", "pinyin":"hǎo", "chinese":"好", "english":"good" },
    { "lesson":"1", "pinyin":"zàijiàn", "chinese":"再见", "english":"goodbye" },
    { "lesson":"1", "pinyin":"búkèqi", "chinese":"不客气", "english":"you're welcome" },
    { "lesson":"1", "pinyin":"bù", "chinese":"不", "english":"no" },
    { "lesson":"1", "pinyin":"kèqi", "chinese":"客气", "english":"polite" },
    { "lesson":"2", "pinyin":"jiào", "chinese":"叫", "english":"called" },
    { "lesson":"2", "pinyin":"shénme", "chinese":"什么", "english":"what" },
    { "lesson":"2", "pinyin":"míngzi", "chinese":"名字", "english":"name" },
    { "lesson":"2", "pinyin":"wǒ", "chinese":"我", "english":"I,me" },
    { "lesson":"2", "pinyin":"Líndá", "chinese":"林达", "english":"Linda" },
    { "lesson":"2", "pinyin":"Mǎkě", "chinese":"马可", "english":"Mark" },
    { "lesson":"2", "pinyin":"nǐmen", "chinese":"你们", "english":"you (plural)" },
    { "lesson":"2", "pinyin":"lǎoshī", "chinese":"老师", "english":"teacher" },
    { "lesson":"2", "pinyin":"nín", "chinese":"您", "english":"you (polite)" },
    { "lesson":"2", "pinyin":"guì", "chinese":"贵", "english":"honourable" },
    { "lesson":"2", "pinyin":"xìng", "chinese":"姓", "english":"surname" },
    { "lesson":"2", "pinyin":"LǐLán", "chinese":"李兰", "english":"Li Lan" },
    { "lesson":"3", "pinyin":"WángDàyáng", "chinese":"王大阳", "english":"Wang Dayang" },
    { "lesson":"3", "pinyin":"hěn", "chinese":"很", "english":"very" },
    { "lesson":"3", "pinyin":"gāoxìng", "chinese":"高兴", "english":"glad" },
    { "lesson":"3", "pinyin":"rènshi", "chinese":"认识", "english":"to get to know" },
    { "lesson":"3", "pinyin":"yě", "chinese":"也", "english":"also" },
    { "lesson":"3", "pinyin":"shì", "chinese":"是", "english":"to be" },
    { "lesson":"3", "pinyin":"nǎ", "chinese":"哪", "english":"which" },
    { "lesson":"3", "pinyin":"Zhōngguórén", "chinese":"中国人", "english":"Chinese person/people" },
    { "lesson":"3", "pinyin":"Zhōngguó", "chinese":"中国", "english":"China" },
    { "lesson":"3", "pinyin":"rén", "chinese":"人", "english":"person/people" },
    { "lesson":"3", "pinyin":"ne", "chinese":"呢", "english":"interrogative particle" },
    { "lesson":"3", "pinyin":"Yīngguórén", "chinese":"英国人", "english":"British" },
    { "lesson":"3", "pinyin":"Yīngguó", "chinese":"英国", "english":"UK" },
    { "lesson":"3", "pinyin":"Dàwèi", "chinese":"大卫", "english":"David" },
    { "lesson":"3", "pinyin":"xuésheng", "chinese":"学生", "english":"student" },
    { "lesson":"3", "pinyin":"xuéxí", "chinese":"学习", "english":"to study" },
    { "lesson":"3", "pinyin":"Hànyǔ", "chinese":"汉语", "english":"Chinese language" },
    { "lesson":"3", "pinyin":"Yīngyǔ", "chinese":"英语", "english":"English language" },
    { "lesson":"3", "pinyin":"zhè", "chinese":"这", "english":"this" },
    { "lesson":"3", "pinyin":"ma", "chinese":"吗", "english":"interrogative particle" },
];
